import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";
import { legalMatch, safeNumber, scoreOpportunity, shouldKeepOpportunity } from "../_shared/opportunity.ts";

const CORS={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Content-Type":"application/json"};
const json=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:CORS});
function normalizeKey(v:string){return v.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"_").replace(/^_|_$/g,"")}
function parseCsvLine(line:string,delimiter:string){const out:string[]=[];let cur="",quoted=false;for(let i=0;i<line.length;i++){const ch=line[i];if(ch==='"'){if(quoted&&line[i+1]==='"'){cur+='"';i++}else quoted=!quoted}else if(ch===delimiter&&!quoted){out.push(cur.trim());cur=""}else cur+=ch}out.push(cur.trim());return out}
function parseCsv(csv:string,delimiter:string){const lines=csv.replace(/^\uFEFF/,"").split(/\r?\n/).filter(x=>x.trim());if(lines.length<2)return[];const headers=parseCsvLine(lines[0],delimiter).map(normalizeKey);return lines.slice(1).map(line=>{const values=parseCsvLine(line,delimiter),row:any={};headers.forEach((h,i)=>row[h]=values[i]??"");return row})}
function first(row:any,names:string[]){for(const n of names){const key=normalizeKey(n);if(row[key]!==undefined&&row[key]!=="")return row[key]}return null}
function brl(v:any){if(v===null||v===undefined||v==="")return null;if(typeof v==="number")return v;const s=String(v).trim();if(s.includes(",")){const n=Number(s.replace(/[^0-9,.-]/g,"").replaceAll(".","").replace(",","."));return Number.isFinite(n)?n:null}return safeNumber(s.replace(/[^0-9.-]/g,""))}
function normalized(row:any,index:number){const object=String(first(row,["objeto","objeto_licitacao","descricao","descricao_objeto","servico"])??"");const title=String(first(row,["titulo","licitacao","edital","numero_edital"])??object??`WaveCode ${index+1}`);const process=first(row,["processo","numero_processo","n_processo","pregao","numero_pregao"]);const id=String(first(row,["id","codigo","identificador","numero_controle_pncp","numero_edital"])??process??`wavecode-${crypto.randomUUID()}`);return{id,title,object,buyer:first(row,["orgao","orgao_publico","comprador","unidade_compradora","entidade"]),city:first(row,["cidade","municipio"]),state:first(row,["uf","estado"]),modality:first(row,["modalidade"]),process,value:brl(first(row,["valor","valor_estimado","valor_total","valor_estimado_total"])),published:first(row,["publicacao","data_publicacao","data_de_publicacao"]),deadline:first(row,["prazo","data_encerramento","encerramento","data_fim_proposta"]),url:first(row,["url","link","link_edital","link_licitacao"]),payload:row}}
Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:CORS});if(req.method!=="POST")return json({error:"Use POST"},405);try{const b=await req.json().catch(()=>({})),o=b.organization_id;if(!o)return json({error:"organization_id is required"},400);let rows:any[]=[];if(Array.isArray(b.rows))rows=b.rows.map((r:any)=>Object.fromEntries(Object.entries(r).map(([k,v])=>[normalizeKey(k),v])));else if(typeof b.csv==="string")rows=parseCsv(b.csv,String(b.delimiter??";"));else return json({error:"Envie rows[] ou csv"},400);const U=Deno.env.get("SUPABASE_URL"),K=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!U||!K)throw new Error("Missing Supabase server secrets");const s=createClient(U,K),items=rows.map(normalized);const raw=items.map(n=>({source:"WaveCode",external_id:n.id,source_url:n.url,title:n.title,buyer_name:n.buyer,city:n.city,state:n.state,modality:n.modality,process_number:n.process,estimated_value:n.value,published_at:n.published,deadline_at:n.deadline,payload:n.payload,last_seen_at:new Date().toISOString()}));const{data:stored,error}=await s.from("raw_notices").upsert(raw,{onConflict:"source,external_id"}).select("id,external_id");if(error)throw error;const ids=new Map((stored??[]).map((r:any)=>[String(r.external_id),String(r.id)])),qualified=items.filter(n=>shouldKeepOpportunity(`${n.title} ${n.object}`,n.value)).map(n=>{const text=`${n.title} ${n.object}`,m=legalMatch(text);return{organization_id:o,raw_notice_id:ids.get(n.id)??null,external_id:n.id,source:"WaveCode",source_url:n.url,title:n.title,buyer_name:n.buyer,buyer_cnpj:null,city:n.city,state:n.state,sphere:null,process_number:n.process,modality:n.modality,object_text:n.object,estimated_value:n.value,published_at:n.published,deadline_at:n.deadline,score:scoreOpportunity(text,n.value,n.deadline),legal_relevant:true,qualification_reason:{strong_terms:m.strong,broad_terms:m.broad,minimum_value:n.value===null?"unknown":n.value>=300000},raw_payload:n.payload,collected_at:new Date().toISOString(),updated_at:new Date().toISOString()}});if(qualified.length){const{error:e}=await s.from("opportunities").upsert(qualified,{onConflict:"organization_id,source,external_id"});if(e)throw e}await s.from("source_health").upsert({source:"WaveCode",category:"aggregator_import",enabled:true,status:"online",last_run_at:new Date().toISOString(),last_success_at:new Date().toISOString(),last_error:null,last_scanned:rows.length,last_qualified:qualified.length,updated_at:new Date().toISOString()},{onConflict:"source"});return json({source:"WaveCode",scanned:rows.length,raw_upserted:stored?.length??0,qualified:qualified.length})}catch(e){return json({error:e instanceof Error?e.message:String(e)},500)}});
