import { useMemo, useState } from 'react'
import { Bell, Bookmark, Building2, CalendarClock, CircleDollarSign, FileSearch, Filter, Gauge, LayoutDashboard, Search, Settings, ShieldCheck, Sparkles, Target, TrendingUp, Users, ListTodo } from 'lucide-react'
import { collaboratorMetrics, opportunities, pendingItems } from './data'

const money = new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0})
type View = 'dashboard'|'radar'|'pending'|'team'|'process'

function daysUntil(date:string){ const [d,m,y]=date.split('/').map(Number); return Math.ceil((new Date(y,m-1,d).getTime()-new Date(2026,7,26).getTime())/86400000) }
function scoreLabel(score:number){ return score>=90?'Alta':score>=75?'Média':'Baixa' }

export default function App(){
 const [view,setView]=useState<View>('dashboard'); const [query,setQuery]=useState(''); const [minimum,setMinimum]=useState(300000); const [highScoreOnly,setHighScoreOnly]=useState(false); const [cpf,setCpf]=useState(''); const [lookup,setLookup]=useState(false)
 const filtered=useMemo(()=>opportunities.filter(x=>`${x.title} ${x.organization} ${x.object} ${x.city} ${x.state}`.toLowerCase().includes(query.toLowerCase())&&(x.estimatedValue??0)>=minimum&&(!highScoreOnly||x.score>=80)),[query,minimum,highScoreOnly])
 const totalValue=filtered.reduce((s,x)=>s+(x.estimatedValue??0),0); const urgent=opportunities.filter(x=>daysUntil(x.deadline)<=7).length
 const nav=(id:View,label:string,Icon:any,count?:number)=><button className={`nav-item ${view===id?'active':''}`} onClick={()=>setView(id)}><Icon size={18}/>{label}{count!==undefined&&<span className="nav-count">{count}</span>}</button>
 return <div className="app-shell">
  <aside className="sidebar"><div className="brand"><div className="brand-mark">N</div><div><strong>Nuvy</strong><span>Legal Radar</span></div></div><div className="workspace"><span>Cliente</span><strong>Auro Nogueira de Barros</strong></div><nav>{nav('dashboard','Visão executiva',LayoutDashboard)}<div className="nav-label">OPORTUNIDADES</div>{nav('radar','Radar de oportunidades',Target,opportunities.length)}<div className="nav-label">OPERAÇÃO</div>{nav('pending','Fila de pendências',ListTodo,pendingItems.filter(x=>x.status!=='Concluído').length)}{nav('team','Desempenho da equipe',Users)}<div className="nav-label">PROCESSUAL</div>{nav('process','Consulta Escavador',ShieldCheck)}</nav><button className="nav-item settings-link"><Settings size={18}/>Configurações</button></aside>
  <main><header className="topbar"><div className="global-search"><Search size={18}/><input placeholder="Buscar oportunidade, órgão ou processo..." value={query} onChange={e=>setQuery(e.target.value)}/></div><button className="icon-button"><Bell size={19}/><span className="notification-dot"/></button><div className="user-chip"><div className="avatar">AN</div><div><strong>Administrador</strong><span>Nuvy Legal Radar</span></div></div></header>
  <div className="page-content">
   {view==='dashboard'&&<><section className="page-heading"><div><span className="kicker">MONITORAMENTO INTELIGENTE</span><h1>Painel executivo</h1><p>Oportunidades jurídicas acima de R$ 300 mil, priorizadas por valor, aderência e prazo.</p></div><button className="primary-button" onClick={()=>setView('radar')}><Sparkles size={17}/>Ver radar</button></section><section className="stats-grid"><div className="stat-card"><div className="stat-icon"><FileSearch size={20}/></div><div><span>Oportunidades</span><strong>{opportunities.length}</strong><small>fontes monitoradas</small></div></div><div className="stat-card"><div className="stat-icon"><CircleDollarSign size={20}/></div><div><span>Valor potencial</span><strong>{money.format(opportunities.reduce((s,x)=>s+(x.estimatedValue??0),0))}</strong><small>carteira atual</small></div></div><div className="stat-card urgent"><div className="stat-icon"><CalendarClock size={20}/></div><div><span>Prazo em 7 dias</span><strong>{urgent}</strong><small>exigem atenção</small></div></div><div className="stat-card"><div className="stat-icon"><Gauge size={20}/></div><div><span>Pendências urgentes</span><strong>{pendingItems.filter(x=>x.status==='Urgente').length}</strong><small>follow-up prioritário</small></div></div></section><section className="radar-panel"><div className="results-heading"><div><strong>Prioridades de hoje</strong><span> ordenadas por aderência</span></div></div><div className="opportunity-list">{opportunities.slice().sort((a,b)=>b.score-a.score).slice(0,3).map(x=><article className="opportunity-card" key={x.id}><div className="opportunity-top"><div className="score-box"><strong>{x.score}</strong><span>score</span></div><div className="opportunity-heading"><div className="eyebrow-row"><span className="source-pill">{x.source}</span><span>{scoreLabel(x.score)} aderência</span></div><h3>{x.title}</h3><p className="organization"><Building2 size={15}/>{x.organization}</p></div></div><div className="opportunity-metrics"><div><span>Valor</span><strong>{money.format(x.estimatedValue??0)}</strong></div><div><span>Prazo</span><strong>{x.deadline}</strong></div><div><span>Situação</span><strong>{x.status}</strong></div><div><span>Origem</span><strong>{x.source}</strong></div></div></article>)}</div></section></>}
   {view==='radar'&&<><section className="page-heading"><div><span className="kicker">CENTRAL DE INTELIGÊNCIA</span><h1>Radar de oportunidades</h1><p>Filtro obrigatório a partir de R$ 300 mil e classificação de aderência.</p></div><button className="primary-button"><Sparkles size={17}/>Executar varredura</button></section><section className="radar-panel"><div className="panel-toolbar"><div className="search-field"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar..."/></div><div className="quick-filters">{[300000,500000,1000000].map(v=><button key={v} className={`filter-chip ${minimum===v?'active':''}`} onClick={()=>setMinimum(v)}>≥ {money.format(v)}</button>)}<button className={`filter-chip ${highScoreOnly?'active':''}`} onClick={()=>setHighScoreOnly(!highScoreOnly)}><Filter size={15}/>Aderência alta</button></div></div><div className="results-heading"><div><strong>{filtered.length} oportunidades</strong><span> · {money.format(totalValue)} em valor estimado</span></div></div><div className="opportunity-list">{filtered.map(x=><article className="opportunity-card" key={x.id}><div className="opportunity-top"><div className="score-box"><strong>{x.score}</strong><span>score</span></div><div className="opportunity-heading"><div className="eyebrow-row"><span className="source-pill">{x.source}</span><span>{x.sphere}</span><span>{x.state}</span></div><h3>{x.title}</h3><p className="organization"><Building2 size={15}/>{x.organization} · {x.city}/{x.state}</p></div><button className={`icon-button ${x.favorite?'active':''}`}><Bookmark size={18}/></button></div><p className="object-text">{x.object}</p><div className="opportunity-metrics"><div><span>Valor estimado</span><strong>{money.format(x.estimatedValue??0)}</strong></div><div><span>Prazo</span><strong>{x.deadline}</strong></div><div><span>Aderência</span><strong>{scoreLabel(x.score)}</strong></div><div><span>Status</span><strong>{x.status}</strong></div></div><div className="ai-summary"><Sparkles size={17}/><p><b>Leitura rápida:</b> {x.summary}</p></div></article>)}</div></section></>}
   {view==='pending'&&<><section className="page-heading"><div><span className="kicker">FOLLOW-UP</span><h1>Fila de pendências</h1><p>Documentos e informações solicitados ao cliente, com prazo, urgência e responsável.</p></div><button className="primary-button">Nova pendência</button></section><section className="radar-panel"><div className="opportunity-list">{pendingItems.map(x=><article className="opportunity-card" key={x.id}><div className="results-heading"><div><strong>{x.client}</strong><span> · {x.request}</span></div><span className="source-pill">{x.urgency}</span></div><div className="opportunity-metrics"><div><span>Responsável</span><strong>{x.owner}</strong></div><div><span>Prazo</span><strong>{x.dueAt}</strong></div><div><span>Status</span><strong>{x.status}</strong></div><div><span>Ação</span><strong>Fazer follow-up</strong></div></div></article>)}</div></section></>}
   {view==='team'&&<><section className="page-heading"><div><span className="kicker">INDICADORES</span><h1>Desempenho por colaborador</h1><p>Tempo médio de resposta e indicadores operacionais, conforme dados disponíveis na integração.</p></div></section><section className="stats-grid">{collaboratorMetrics.map(x=><div className="stat-card" key={x.id}><div className="stat-icon"><Users size={20}/></div><div><span>{x.name}</span><strong>{x.averageResponseMinutes} min</strong><small>{x.handled} atendimentos · {x.pending} pendências</small></div></div>)}</section></>}
   {view==='process'&&<><section className="page-heading"><div><span className="kicker">MÓDULO INDEPENDENTE</span><h1>Consulta processual</h1><p>Consulta por CPF e resumo de andamento via integração com Escavador.</p></div></section><section className="radar-panel"><div className="panel-toolbar"><div className="search-field"><Search size={18}/><input value={cpf} onChange={e=>setCpf(e.target.value)} placeholder="Digite o CPF"/></div><button className="primary-button" onClick={()=>setLookup(true)}>Consultar</button></div>{lookup&&<div className="ai-summary"><ShieldCheck size={18}/><p><b>Integração aguardando credenciais do Escavador.</b> A interface e o fluxo estão preparados. A consulta real só deve ser ativada após aprovação/configuração da API do fornecedor.</p></div>}</section></>}
  </div></main>
 </div>
}
