import { useEffect, useMemo, useState } from 'react'
import { Bell, Bookmark, Building2, CalendarClock, CircleDollarSign, Database, FileSearch, Filter, Gauge, LayoutDashboard, Link2, ListTodo, LogOut, Plus, RefreshCw, Search, Settings, ShieldCheck, Target, Users } from 'lucide-react'
import { supabase } from './lib/supabase'

type View='dashboard'|'radar'|'sources'|'pending'|'team'|'process'|'settings'
type DbOpportunity={id:string;title:string;buyer_name:string|null;city:string|null;state:string|null;sphere:string|null;process_number:string|null;modality:string|null;object_text:string|null;estimated_value:number|null;published_at:string|null;deadline_at:string|null;source:string;source_url:string|null;status:string;score:number;ai_summary:string|null;is_favorite:boolean}
type Pending={id:string;client_name:string;request_text:string;owner_name:string|null;due_at:string;urgency:string;status:string}
type Metric={id:string;collaborator_name:string;response_minutes:number;interaction_at:string}
type Connector={id:string;name:string;category:string;url:string;kind:string;enabled:boolean;last_success_at:string|null;last_error:string|null}

const money=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0})
const dateFmt=new Intl.DateTimeFormat('pt-BR')
const fallbackOrgId='0701a783-4982-4288-8328-08c11a9f0b9b'
const statuses=['Novo','Em análise','Interessante','Participaremos','Documentação','Proposta em elaboração','Enviado','Aguardando resultado','Ganho','Perdido','Descartado']
const fmtDate=(v:string|null)=>{if(!v)return'Não informado';const d=new Date(v);return Number.isNaN(d.getTime())?v:dateFmt.format(d)}
const daysUntil=(v:string|null)=>v?Math.ceil((new Date(v).getTime()-Date.now())/86400000):9999
const scoreLabel=(s:number)=>s>=85?'Alta':s>=65?'Média':'Baixa'

export default function App(){
 const[view,setView]=useState<View>('dashboard');const[query,setQuery]=useState('');const[minimum,setMinimum]=useState(300000);const[highScoreOnly,setHighScoreOnly]=useState(false);const[sourceFilter,setSourceFilter]=useState('Todas');const[stateFilter,setStateFilter]=useState('Todos');const[session,setSession]=useState<any>(null);const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[authMode,setAuthMode]=useState<'login'|'signup'>('login');const[authMessage,setAuthMessage]=useState('');const[opportunities,setOpportunities]=useState<DbOpportunity[]>([]);const[pending,setPending]=useState<Pending[]>([]);const[metrics,setMetrics]=useState<Metric[]>([]);const[connectors,setConnectors]=useState<Connector[]>([]);const[orgId,setOrgId]=useState(fallbackOrgId);const[loading,setLoading]=useState(true);const[syncing,setSyncing]=useState(false);const[syncMessage,setSyncMessage]=useState('');const[syncReport,setSyncReport]=useState<any[]>([]);const[cpf,setCpf]=useState('');const[lookup,setLookup]=useState(false);const[newPending,setNewPending]=useState(false);const[pClient,setPClient]=useState('');const[pRequest,setPRequest]=useState('');const[pDue,setPDue]=useState('');const[newConnector,setNewConnector]=useState(false);const[cName,setCName]=useState('');const[cUrl,setCUrl]=useState('');const[cCategory,setCCategory]=useState('municipal_portal')
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);setLoading(false)});const{data:sub}=supabase.auth.onAuthStateChange((_e,n)=>setSession(n));return()=>sub.subscription.unsubscribe()},[])
 useEffect(()=>{if(session)void bootstrap()},[session])
 async function bootstrap(){setLoading(true);const{data:members}=await supabase.from('organization_members').select('organization_id').limit(1);const currentOrg=members?.[0]?.organization_id||fallbackOrgId;setOrgId(currentOrg);await Promise.all([loadOpportunities(currentOrg),loadPending(currentOrg),loadMetrics(currentOrg),loadConnectors(currentOrg)]);setLoading(false)}
 async function loadOpportunities(o=orgId){const{data,error}=await supabase.from('opportunities').select('*').eq('organization_id',o).order('score',{ascending:false}).limit(2000);if(error)setSyncMessage(`Erro ao carregar oportunidades: ${error.message}`);else setOpportunities((data??[]) as DbOpportunity[])}
 async function loadPending(o=orgId){const{data}=await supabase.from('pending_items').select('*').eq('organization_id',o).order('due_at',{ascending:true});setPending((data??[]) as Pending[])}
 async function loadMetrics(o=orgId){const{data}=await supabase.from('response_metrics').select('*').eq('organization_id',o).order('interaction_at',{ascending:false}).limit(5000);setMetrics((data??[]) as Metric[])}
 async function loadConnectors(o=orgId){const{data}=await supabase.from('source_connectors').select('*').or(`organization_id.is.null,organization_id.eq.${o}`).order('name');setConnectors((data??[]) as Connector[])}
 async function authenticate(){setAuthMessage('');const r=authMode==='signup'?await supabase.auth.signUp({email,password}):await supabase.auth.signInWithPassword({email,password});if(r.error)setAuthMessage(r.error.message);else setAuthMessage(authMode==='signup'?'Conta criada. Entre após confirmar o e-mail, se solicitado.':'Acesso realizado.')}
 async function runSync(){setSyncing(true);setSyncMessage('Varredura em andamento...');setSyncReport([]);const{data,error}=await supabase.functions.invoke('sync-all',{body:{organization_id:orgId,days_back:45,days_ahead:150,max_pages:150,include_legacy:true}});if(error){setSyncMessage(`Falha na varredura: ${error.message}`)}else{const results=data?.results??[];setSyncReport(results);const selected=results.reduce((s:number,x:any)=>s+Number(x?.payload?.selected??0),0);const scanned=results.reduce((s:number,x:any)=>s+Number(x?.payload?.scanned??0),0);setSyncMessage(`Varredura concluída: ${scanned.toLocaleString('pt-BR')} registros lidos e ${selected.toLocaleString('pt-BR')} oportunidades jurídicas selecionadas.`);await loadOpportunities(orgId)}setSyncing(false)}
 async function toggleFavorite(x:DbOpportunity){const next=!x.is_favorite;const{error}=await supabase.from('opportunities').update({is_favorite:next}).eq('id',x.id);if(!error)setOpportunities(v=>v.map(i=>i.id===x.id?{...i,is_favorite:next}:i))}
 async function updateStatus(x:DbOpportunity,status:string){const{error}=await supabase.from('opportunities').update({status,updated_at:new Date().toISOString()}).eq('id',x.id);if(!error)setOpportunities(v=>v.map(i=>i.id===x.id?{...i,status}:i))}
 async function createPending(){if(!pClient||!pRequest||!pDue)return;await supabase.from('pending_items').insert({organization_id:orgId,client_name:pClient,request_text:pRequest,due_at:new Date(pDue).toISOString(),urgency:'Normal',status:'Aguardando cliente'});setPClient('');setPRequest('');setPDue('');setNewPending(false);await loadPending(orgId)}
 async function createConnector(){if(!cName||!cUrl)return;await supabase.from('source_connectors').insert({organization_id:orgId,name:cName,url:cUrl,category:cCategory,kind:'json',config:{},enabled:true});setCName('');setCUrl('');setNewConnector(false);await loadConnectors(orgId)}
 const sources=useMemo(()=>['Todas',...Array.from(new Set(opportunities.map(x=>x.source))).sort()],[opportunities]);const states=useMemo(()=>['Todos',...Array.from(new Set(opportunities.map(x=>x.state).filter(Boolean) as string[])).sort()],[opportunities])
 const filtered=useMemo(()=>opportunities.filter(x=>{const hay=`${x.title} ${x.buyer_name??''} ${x.object_text??''} ${x.city??''} ${x.state??''} ${x.process_number??''}`.toLowerCase();return hay.includes(query.toLowerCase())&&(x.estimated_value===null||x.estimated_value>=minimum)&&(!highScoreOnly||x.score>=80)&&(sourceFilter==='Todas'||x.source===sourceFilter)&&(stateFilter==='Todos'||x.state===stateFilter)}),[opportunities,query,minimum,highScoreOnly,sourceFilter,stateFilter])
 const totalValue=opportunities.reduce((s,x)=>s+(x.estimated_value??0),0),urgent=opportunities.filter(x=>{const d=daysUntil(x.deadline_at);return d>=0&&d<=7}).length,favorites=opportunities.filter(x=>x.is_favorite).length
 const groupedSources=useMemo(()=>Array.from(new Set(opportunities.map(x=>x.source))).map(source=>({source,count:opportunities.filter(x=>x.source===source).length,value:opportunities.filter(x=>x.source===source).reduce((s,x)=>s+(x.estimated_value??0),0)})).sort((a,b)=>b.count-a.count),[opportunities])
 const team=useMemo(()=>{const map=new Map<string,number[]>();metrics.forEach(m=>{if(!map.has(m.collaborator_name))map.set(m.collaborator_name,[]);map.get(m.collaborator_name)!.push(Number(m.response_minutes))});return Array.from(map.entries()).map(([name,v])=>({name,avg:Math.round(v.reduce((a,b)=>a+b,0)/v.length),count:v.length}))},[metrics])
 if(loading&&!session)return <div className="auth-shell"><div className="auth-card"><h2>Nuvy</h2><p>Conectando ao radar de licitações...</p></div></div>
 if(!session)return <div className="auth-shell"><div className="auth-card"><div className="brand auth-brand"><div className="brand-mark">N</div><div><strong>Nuvy</strong><span>Legal Radar</span></div></div><h1>{authMode==='login'?'Entrar':'Criar acesso'}</h1><p>Monitoramento jurídico multi-fonte conectado ao Supabase.</p><input className="auth-input" value={email} onChange={e=>setEmail(e.target.value)} placeholder="E-mail" type="email"/><input className="auth-input" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Senha" type="password"/><button className="primary-button auth-button" onClick={authenticate}>{authMode==='login'?'Entrar':'Criar conta'}</button>{authMessage&&<div className="auth-message">{authMessage}</div>}<button className="link-button" onClick={()=>setAuthMode(authMode==='login'?'signup':'login')}>{authMode==='login'?'Primeiro acesso? Criar conta':'Já tenho conta'}</button></div></div>
 const nav=(id:View,label:string,Icon:any,count?:number)=><button className={`nav-item ${view===id?'active':''}`} onClick={()=>setView(id)}><Icon size={18}/>{label}{count!==undefined&&<span className="nav-count">{count}</span>}</button>
 const Card=({x}:{x:DbOpportunity})=><article className="opportunity-card"><div className="opportunity-top"><div className="score-box"><strong>{x.score}</strong><span>score</span></div><div className="opportunity-heading"><div className="eyebrow-row"><span className="source-pill">{x.source}</span><span>{x.modality||'Modalidade n/i'}</span><span>{x.state||'UF n/i'}</span></div><h3>{x.title}</h3><p className="organization"><Building2 size={15}/>{x.buyer_name||'Órgão não identificado'}{x.city?` · ${x.city}/${x.state??''}`:''}</p></div><button className={`icon-button ${x.is_favorite?'active':''}`} onClick={()=>void toggleFavorite(x)}><Bookmark size={18}/></button></div><p className="object-text">{x.object_text||'Objeto não informado pela fonte.'}</p><div className="opportunity-metrics"><div><span>Valor estimado</span><strong>{x.estimated_value===null?'A validar':money.format(x.estimated_value)}</strong></div><div><span>Prazo</span><strong>{fmtDate(x.deadline_at)}</strong></div><div><span>Aderência</span><strong>{scoreLabel(x.score)}</strong></div><div><span>Processo</span><strong>{x.process_number||'n/i'}</strong></div></div><div className="card-footer"><select className="status-select" value={x.status} onChange={e=>void updateStatus(x,e.target.value)}>{statuses.map(s=><option key={s}>{s}</option>)}</select>{x.source_url&&<a className="secondary-button" href={x.source_url} target="_blank" rel="noreferrer"><Link2 size={15}/>Abrir fonte</a>}</div></article>
 return <div className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark">N</div><div><strong>Nuvy</strong><span>Legal Radar</span></div></div><div className="workspace"><span>Ambiente</span><strong>Radar Jurídico Nacional</strong></div><nav>{nav('dashboard','Visão executiva',LayoutDashboard)}<div className="nav-label">INTELIGÊNCIA</div>{nav('radar','Radar de oportunidades',Target,opportunities.length)}{nav('sources','Cobertura de fontes',Database,groupedSources.length+connectors.length)}<div className="nav-label">OPERAÇÃO</div>{nav('pending','Fila de pendências',ListTodo,pending.filter(x=>x.status!=='Concluído').length)}{nav('team','Desempenho da equipe',Users)}<div className="nav-label">PROCESSUAL</div>{nav('process','Consulta Escavador',ShieldCheck)}</nav><button className={`nav-item settings-link ${view==='settings'?'active':''}`} onClick={()=>setView('settings')}><Settings size={18}/>Configurações</button></aside><main><header className="topbar"><div className="global-search"><Search size={18}/><input placeholder="Buscar órgão, processo, objeto ou município..." value={query} onChange={e=>setQuery(e.target.value)}/></div><button className="icon-button"><Bell size={19}/></button><div className="user-chip"><div className="avatar">NU</div><div><strong>Administrador</strong><span>{session.user?.email}</span></div></div><button className="icon-button" onClick={()=>void supabase.auth.signOut()}><LogOut size={18}/></button></header><div className="page-content">
 {view==='dashboard'&&<><section className="hero-panel"><div><span className="kicker">RADAR JURÍDICO NACIONAL</span><h1>Monitoramento multi-fonte em tempo real</h1><p>PNCP, Compras.gov.br, legado federal e conectores estaduais, municipais e diários oficiais no mesmo funil.</p></div><button className="primary-button" onClick={()=>void runSync()} disabled={syncing}><RefreshCw size={17}/>{syncing?'Varrendo fontes...':'Executar varredura completa'}</button></section>{syncMessage&&<div className="sync-banner">{syncMessage}</div>}{syncReport.length>0&&<div className="sync-report">{syncReport.map((r:any)=><div key={r.function}><strong>{r.function}</strong><span>{r.ok?'OK':'Falha'} · {Number(r.payload?.scanned??0).toLocaleString('pt-BR')} lidos · {Number(r.payload?.selected??0).toLocaleString('pt-BR')} selecionados</span></div>)}</div>}<section className="stats-grid"><div className="stat-card"><div className="stat-icon"><FileSearch size={20}/></div><div><span>Oportunidades</span><strong>{opportunities.length}</strong><small>no banco</small></div></div><div className="stat-card"><div className="stat-icon"><CircleDollarSign size={20}/></div><div><span>Valor potencial</span><strong>{money.format(totalValue)}</strong><small>valor conhecido</small></div></div><div className="stat-card urgent"><div className="stat-icon"><CalendarClock size={20}/></div><div><span>Prazo em 7 dias</span><strong>{urgent}</strong><small>atenção imediata</small></div></div><div className="stat-card"><div className="stat-icon"><Bookmark size={20}/></div><div><span>Favoritas</span><strong>{favorites}</strong><small>priorizadas</small></div></div></section><section className="dashboard-grid"><div className="radar-panel"><div className="results-heading"><strong>Top oportunidades</strong><span>Maior aderência primeiro</span></div><div className="opportunity-list">{opportunities.slice(0,5).map(x=><Card key={x.id} x={x}/>)}{!opportunities.length&&<div className="empty-state"><Target size={28}/><strong>Nenhuma oportunidade ainda</strong><span>Execute a primeira varredura para alimentar o radar.</span></div>}</div></div><div className="radar-panel"><div className="results-heading"><strong>Cobertura por fonte</strong><span>{groupedSources.length} fontes ativas com resultado</span></div><div className="source-list">{groupedSources.slice(0,8).map(s=><div className="source-row" key={s.source}><div><strong>{s.source}</strong><span>{s.count} oportunidades</span></div><b>{money.format(s.value)}</b></div>)}{!groupedSources.length&&<div className="empty-state small"><Database size={24}/><span>Aguardando primeira coleta.</span></div>}</div></div></section></>}
 {view==='radar'&&<><section className="page-heading"><div><span className="kicker">CENTRAL DE INTELIGÊNCIA</span><h1>Radar de oportunidades</h1><p>Busca, qualificação, priorização e acompanhamento no mesmo painel.</p></div><button className="primary-button" onClick={()=>void runSync()} disabled={syncing}><RefreshCw size={17}/>{syncing?'Varrendo...':'Atualizar radar'}</button></section><section className="radar-panel"><div className="panel-toolbar"><div className="search-field"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar..."/></div><select className="filter-select" value={sourceFilter} onChange={e=>setSourceFilter(e.target.value)}>{sources.map(s=><option key={s}>{s}</option>)}</select><select className="filter-select" value={stateFilter} onChange={e=>setStateFilter(e.target.value)}>{states.map(s=><option key={s}>{s}</option>)}</select><div className="quick-filters">{[300000,500000,1000000].map(v=><button key={v} className={`filter-chip ${minimum===v?'active':''}`} onClick={()=>setMinimum(v)}>≥ {money.format(v)}</button>)}<button className={`filter-chip ${highScoreOnly?'active':''}`} onClick={()=>setHighScoreOnly(!highScoreOnly)}><Filter size={15}/>Score 80+</button></div></div><div className="results-heading"><div><strong>{filtered.length} oportunidades</strong><span> · {money.format(filtered.reduce((s,x)=>s+(x.estimated_value??0),0))}</span></div></div><div className="opportunity-list">{filtered.map(x=><Card key={x.id} x={x}/>)}</div></section></>}
 {view==='sources'&&<><section className="page-heading"><div><span className="kicker">COBERTURA</span><h1>Fontes monitoradas</h1><p>Visibilidade sobre PNCP, Compras.gov.br e conectores adicionais.</p></div><button className="primary-button" onClick={()=>setNewConnector(!newConnector)}><Plus size={16}/>Adicionar fonte</button></section>{newConnector&&<section className="form-panel"><input className="auth-input" placeholder="Nome da fonte" value={cName} onChange={e=>setCName(e.target.value)}/><input className="auth-input" placeholder="URL JSON ou endpoint" value={cUrl} onChange={e=>setCUrl(e.target.value)}/><select className="auth-input" value={cCategory} onChange={e=>setCCategory(e.target.value)}><option value="municipal_portal">Portal municipal</option><option value="state_portal">Portal estadual</option><option value="official_diary">Diário oficial</option><option value="private_public_source">Fonte privada pública</option></select><button className="primary-button" onClick={()=>void createConnector()}>Salvar conector</button></section>}<section className="source-grid"><div className="source-card featured"><Database size={22}/><strong>PNCP</strong><span>Coletor nativo com paginação ampla</span><b>{opportunities.filter(x=>x.source==='PNCP').length} oportunidades</b></div><div className="source-card featured"><Database size={22}/><strong>Compras.gov.br Legado</strong><span>Base federal histórica e atual</span><b>{opportunities.filter(x=>x.source==='Compras.gov.br Legado').length} oportunidades</b></div>{connectors.map(c=><div className="source-card" key={c.id}><Database size={22}/><strong>{c.name}</strong><span>{c.category} · {c.kind.toUpperCase()}</span><b>{c.enabled?'Ativo':'Pausado'}</b>{c.last_error&&<small>{c.last_error}</small>}</div>)}</section></>}
 {view==='pending'&&<><section className="page-heading"><div><span className="kicker">FOLLOW-UP</span><h1>Fila de pendências</h1><p>Prazos de documentos e informações pendentes do cliente.</p></div><button className="primary-button" onClick={()=>setNewPending(!newPending)}><Plus size={16}/>Nova pendência</button></section>{newPending&&<section className="form-panel"><input className="auth-input" placeholder="Cliente" value={pClient} onChange={e=>setPClient(e.target.value)}/><input className="auth-input" placeholder="Documento ou informação solicitada" value={pRequest} onChange={e=>setPRequest(e.target.value)}/><input className="auth-input" type="datetime-local" value={pDue} onChange={e=>setPDue(e.target.value)}/><button className="primary-button" onClick={()=>void createPending()}>Salvar</button></section>}<section className="radar-panel"><div className="opportunity-list">{pending.map(x=><article className="opportunity-card" key={x.id}><div className="results-heading"><strong>{x.client_name}</strong><span className="source-pill">{x.urgency}</span></div><p className="object-text">{x.request_text}</p><div className="opportunity-metrics"><div><span>Responsável</span><strong>{x.owner_name||'Não definido'}</strong></div><div><span>Prazo</span><strong>{fmtDate(x.due_at)}</strong></div><div><span>Status</span><strong>{x.status}</strong></div><div><span>Prioridade</span><strong>{daysUntil(x.due_at)<=1?'Imediata':daysUntil(x.due_at)<=3?'Alta':'Normal'}</strong></div></div></article>)}{!pending.length&&<div className="empty-state"><ListTodo size={26}/><strong>Nenhuma pendência cadastrada</strong></div>}</div></section></>}
 {view==='team'&&<><section className="page-heading"><div><span className="kicker">INDICADORES</span><h1>Desempenho da equipe</h1><p>Tempo médio de resposta calculado com dados reais de integração.</p></div></section><section className="stats-grid">{team.map(x=><div className="stat-card" key={x.name}><div className="stat-icon"><Users size={20}/></div><div><span>{x.name}</span><strong>{x.avg} min</strong><small>{x.count} interações medidas</small></div></div>)}{!team.length&&<div className="empty-state wide"><Users size={26}/><strong>Sem métricas ainda</strong><span>Os indicadores aparecem quando a integração alimentar response_metrics.</span></div>}</section></>}
 {view==='process'&&<><section className="page-heading"><div><span className="kicker">PROCESSUAL</span><h1>Consulta Escavador</h1><p>Módulo reservado para consulta processual por CPF.</p></div></section><section className="radar-panel"><div className="panel-toolbar"><div className="search-field"><Search size={18}/><input value={cpf} onChange={e=>setCpf(e.target.value)} placeholder="Digite o CPF"/></div><button className="primary-button" onClick={()=>setLookup(true)}>Consultar</button></div>{lookup&&<div className="ai-summary"><ShieldCheck size={18}/><p><b>Integração preparada.</b> Falta configurar a credencial do Escavador para consultas reais.</p></div>}</section></>}
 {view==='settings'&&<><section className="page-heading"><div><span className="kicker">CONFIGURAÇÃO</span><h1>Ambiente do sistema</h1><p>Resumo técnico da operação atual.</p></div></section><section className="settings-grid"><div className="source-card"><Database size={22}/><strong>Supabase</strong><span>Projeto kdboegkwiqktxykbayeq</span><b>Conectado</b></div><div className="source-card"><Target size={22}/><strong>Corte mínimo</strong><span>Oportunidades com valor conhecido</span><b>R$ 300 mil</b></div><div className="source-card"><Gauge size={22}/><strong>Janela padrão</strong><span>45 dias para trás + 150 à frente</span><b>195 dias</b></div></section></>}
 </div></main></div>
}
