import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";
import { legalMatch, safeNumber, scoreOpportunity, shouldKeepOpportunity } from "../_shared/opportunity.ts";

type Connector={id:string;organization_id:string|null;name:string;category:string;url:string;kind:"json"|"rss";config:Record<string,any>|null};
const CORS={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Content-Type":"application/json"};
const json=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:CORS});
function getPath(obj:any,path?:string|null):any{return !path?obj:path.split(".").reduce((v,k)=>v?.[k],obj)}
function pick(row:any,m:Record<string,string>,f:string){return getPath(row,m[f])}
function decodeXml(v:string){return v.replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,"$1").replaceAll("&amp;","&").replaceAll("&lt;","<").replaceAll("&gt;",">").replaceAll("&quot;",'"').replaceAll("&#39;","'").trim()}
function xmlTag(b:string,names:string[]){for(const n of names){const m=b.match(new RegExp(`<${n}(?:\\s[^>]*)?>([\\s\\S]*?)<\\/${n}>`,"i"));if(m)return decodeXml(m[1].replace(/<[^>]+>/g," "))}return null}
function parseRss(xml:string){return[...xml.matchAll(/<(item|entry)(?:\s[^>]*)?>([\s\S]*?)<\/\1>/gi)].map(m=>{const b=m[2],a=b.match(/<link[^>]+href=["']([^"']+)["']/i);return{title:xmlTag(b,["title"]),description:xmlTag(b,["description","summary","content"]),link:a?.[1]??xmlTag(b,["link","guid","id"]),published:xmlTag(b,["pubDate","published","updated"]),raw:b}})}
function parseBrl(v:string){const n=Number(v.replace(/[^0-9.,]/g,"").replaceAll(".","").replace(",","."));return Number.isFinite(n)?n:null}
async function fetchConnector(c:Connector){const r=await fetch(c.url,{headers:{Accept:c.kind==="rss"?"application/rss+xml, application/atom+xml, text/xml, */*":"application/json","User-Agent":"Nuvy-Licitacoes/2.0"}});if(!r.ok)throw new Error(`${c.name} ${r.status}: ${await r.text()}`);if(c.kind==="rss")return parseRss(await r.text());const p=await r.json(),rows=getPath(p,c.config?.items_path??c.config?.itemsPath??null);if(Array.isArray(rows))return rows;if(Array.isArray(p))return p;throw new Error(`${c.name}: items_path nao aponta para uma lista`)}
function normalizeRow(row:any,c:Connector){const cfg=c.config??{},m=cfg.mapping??{};if(c.kind==="rss"){const text=`${row.title??""} ${row.description??""}`,values=(text.match(/R\$\s?[\d\.]+(?:,\d{2})?/g)??[]).map(parseBrl).filter((v):v is number=>v!==null);return{id:String(row.link??`${c.id}-${String(row.title??"").slice(0,120)}`),title:row.title??"Publicacao em diario oficial",object:row.description??row.title??"",value:values.length?Math.max(...values):null,url:row.link??c.url,buyer:null,city:cfg.city??null,state:cfg.state??null,sphere:cfg.sphere??c.category,process:null,modality:null,published:row.published??null,deadline:null,payload:row}}
 const object=String(pick(row,m,"object")??pick(row,m,"description")??""),title=String(pick(row,m,"title")??object??c.name);return{id:String(pick(row,m,"id")??pick(row,m,"process_number")??`${c.id}-${crypto.randomUUID()}`),title,object,value:safeNumber(pick(row,m,"value")),url:pick(row,m,"url")??c.url,buyer:pick(row,m,"buyer_name")??null,city:pick(row,m,"city")??cfg.city??null,state:pick(row,m,"state")??cfg.state??null,sphere:pick(row,m,"sphere")??cfg.sphere??c.category,process:pick(row,m,"process_number")??null,modality:pick(row,m,"modality")??null,published:pick(row,m,"published_at")??null,deadline:pick(row,m,"deadline")??null,payload:row}}
function rawMapped(n:any,c:Connector){return{source:c.name,external_id:n.id,source_url:n.url,title:n.title,buyer_name:n.buyer,city:n.city,state:n.state,modality:n.modality,process_number:n.process,estimated_value:n.value,published_at:n.published,deadline_at:n.deadline,payload:{...n.payload,_connector:{id:c.id,name:c.name}},last_seen_at:new Date().toISOString()}}
function qualifiedMapped(n:any,c:Connector,o:string,rawId:string|null){const text=`${n.title} ${n.object}`,match=legalMatch(text);return{organization_id:o,raw_notice_id:rawId,external_id:n.id,source:c.name,source_url:n.url,title:n.title,buyer_name:n.buyer,buyer_cnpj:null,city:n.city,state:n.state,sphere:n.sphere,process_number:n.process,modality:n.modality,object_text:n.object,estimated_value:n.value,published_at:n.published,deadline_at:n.deadline,score:scoreOpportunity(text,n.value,n.deadline),legal_relevant:true,qualification_reason:{strong_terms:match.strong,broad_terms:match.broad,minimum_value:n.value===null?"unknown":n.value>=300000},raw_payload:n.payload,collected_at:new Date().toISOString(),updated_at:new Date().toISOString()}}
Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:CORS});if(req.method!=="POST")return json({error:"Use POST"},405);try{const b=await req.json().catch(()=>({})),o=b.organization_id;if(!o)return json({error:"organization_id is required"},400);const U=Deno.env.get("SUPABASE_URL"),K=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!U||!K)throw new Error("Missing Supabase server secrets");const s=createClient(U,K);let q=s.from("source_connectors").select("id,organization_id,name,category,url,kind,config").eq("enabled",true).or(`organization_id.is.null,organization_id.eq.${o}`);if(Array.isArray(b.connector_ids)&&b.connector_ids.length)q=q.in("id",b.connector_ids);const{data,error}=await q;if(error)throw error;let scanned=0,rawCount=0,qualified=0;const reports:any[]=[];for(const c of (data??[]) as Connector[]){const started=Date.now();try{const rows=await fetchConnector(c);scanned+=rows.length;const normalized=rows.map(r=>normalizeRow(r,c));const{data:stored,error:rawError}=await s.from("raw_notices").upsert(normalized.map(n=>rawMapped(n,c)),{onConflict:"source,external_id"}).select("id,external_id");if(rawError)throw rawError;rawCount+=stored?.length??0;const ids=new Map((stored??[]).map((r:any)=>[String(r.external_id),String(r.id)])),selected=normalized.filter(n=>shouldKeepOpportunity(`${n.title} ${n.object}`,n.value)).map(n=>qualifiedMapped(n,c,o,ids.get(n.id)??null));if(selected.length){const{error:e}=await s.from("opportunities").upsert(selected,{onConflict:"organization_id,source,external_id"});if(e)throw e;qualified+=selected.length}await s.from("source_health").upsert({source:c.name,category:c.category,enabled:true,status:"online",last_run_at:new Date().toISOString(),last_success_at:new Date().toISOString(),last_error:null,last_scanned:rows.length,last_qualified:selected.length,avg_duration_ms:Date.now()-started,updated_at:new Date().toISOString()},{onConflict:"source"});reports.push({connector:c.name,status:"ok",scanned:rows.length,raw_upserted:stored?.length??0,qualified:selected.length})}catch(e){const msg=e instanceof Error?e.message:String(e);await s.from("source_health").upsert({source:c.name,category:c.category,enabled:true,status:"offline",last_run_at:new Date().toISOString(),last_error:msg,last_scanned:0,last_qualified:0,updated_at:new Date().toISOString()},{onConflict:"source"});reports.push({connector:c.name,status:"error",error:msg})}}return json({source:"configured-sources",connectors:(data??[]).length,scanned,raw_upserted:rawCount,qualified,reports})}catch(e){return json({error:e instanceof Error?e.message:String(e)},500)}});
